spring.datasource.url=${DB_JDBC_URL:jdbc:postgresql://host.docker.internal:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.show-sql=${LOG_JPA_SQL:true}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.web.error.include-stacktrace=${INCLUDE_STACKTRACE:never}
logging.level.org.springframework.web.server.adapter.HttpWebHandlerAdapter=${LOG_HTTP_WEB_HANDLER:DEBUG}
logging.level.com.iron.tec.labs.ecommercejava=${LOG_ECOMMERCE:DEBUG}
spring.messages.basename=${MESSAGES_BASENAME:i18n/messages}

spring.mail.host=${MAIL_HOST:smtp.ethereal.email}
spring.mail.port=${MAIL_PORT:587}

spring.mail.username=${MAIL_USERNAME:beaulah.jaskolski6@ethereal.email}
spring.mail.password=${MAIL_PASSWORD:kFhzSmU5zwsmkwU1Kq}

spring.mail.properties.mail.transport.protocol=${MAIL_PROTOCOL:smtp}
spring.mail.properties.mail.smtp.auth=${MAIL_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_START_TLS:true}
spring.mail.properties.mail.debug=${MAIL_DEBUG:true}
spring.docker.compose.enabled=${DOCKER_COMPOSE_ENABLED:false}

# Application base URL
app.base-url=${APP_BASE_URL:http://localhost:8080}
jwt.secret.key=${JWT_SECRET_KEY:497e5789-db2c-41e7-8071-682721231b18}
jwt.secret.expiration.in.milliseconds=${JWT_SECRET_EXPIRATION_IN_MILLISECONDS:1200000}
spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:true}
spring.liquibase.change-log=${SPRING_LIQUIBASE_PATH:classpath:/db/changelog/changelog.sql}
spring.docker.compose.lifecycle-management=start_only